apiVersion: v1
kind: PersistentVolume
metadata:
  name: %#VOLUME_NAME#%
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-luks-storage-class
  volumeMode: Filesystem
  csi:
    driver: linodebs.csi.linode.com
    fsType: ext4
    nodeStageSecretRef:
      name: my-luks-secret
      namespace: csi-encrypt-keys
    volumeAttributes:
      linodebs.csi.linode.com/luks-cipher: aes-xts-plain64
      linodebs.csi.linode.com/luks-encrypted: "true"
      linodebs.csi.linode.com/luks-key-size: "512"
    volumeHandle: %#VOLUME_HANDLE#%

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-ze-mongodb-0
  namespace: my-namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: my-luks-storage-class
  volumeName: %#VOLUME_NAME#%


